INSERT INTO dbo.Products (name, category, image, new_price, old_price) VALUES
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', './product_1.png', 50.0, 80.5),
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', './product_2.png', 85.0, 120.5),
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', './product_3.png', 60.0, 100.5),
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', './product_4.png', 100.0, 150.0),
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', './product_5.png', 85.0, 120.5),
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', './product_6.png', 85.0, 120.5),
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', './product_7.png', 85.0, 120.5),
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', './product_8.png', 85.0, 120.5),
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', './product_9.png', 85.0, 120.5),
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', './product_10.png', 85.0, 120.5),
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', './product_11.png', 85.0, 120.5),
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', './product_12.png', 85.0, 120.5),
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', './product_13.png', 85.0, 120.5),
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', './product_14.png', 85.0, 120.5),
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', './product_15.png', 85.0, 120.5),
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', './product_16.png', 85.0, 120.5),
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', './product_17.png', 85.0, 120.5),
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', './product_18.png', 85.0, 120.5),
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', './product_19.png', 85.0, 120.5),
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', './product_20.png', 85.0, 120.5),
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', './product_21.png', 85.0, 120.5),
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', './product_22.png', 85.0, 120.5),
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', './product_23.png', 85.0, 120.5),
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', './product_24.png', 85.0, 120.5),
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', './product_25.png', 85.0, 120.5),
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', './product_26.png', 85.0, 120.5),
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', './product_27.png', 85.0, 120.5),
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', './product_28.png', 85.0, 120.5),
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', './product_29.png', 85.0, 120.5),
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', './product_30.png', 85.0, 120.5),
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', './product_31.png', 85.0, 120.5),
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', './product_32.png', 85.0, 120.5),
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', './product_33.png', 85.0, 120.5),
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', './product_34.png', 85.0, 120.5),
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', './product_35.png', 85.0, 120.5),
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', './product_36.png', 85.0, 120.5);